runtime: python39

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /static
  static_dir: static

- url: /.*
  script: auto
